name: Test

on: [push, pull_request]

jobs:
  test_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 3-stage bootstrap
        run: |
          cd ${{ github.workspace }}
          ./meta/bootstrap.sh

      - name: Running tests with self-hosted compiler
        run: |
          cd ${{ github.workspace }}
          python3 meta/test.py -c bootstrap/ocen
